title: DigitalGov Resources
email: DigitalGov@gsa.gov

twitter_username: digitalgov
# github_username:  18F

styles:
  - /assets/uswds/css/uswds.min.css
  - /assets/main.css

# Exlude files from being present in the build site
exclude:
  - ".gitignore"
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - package.json
  - node_modules
  - README.md