title                   : "Digital.gov - Better Digital in Government"
baseURL                 : "/"
languageCode            : "en-us"
theme                   : "digital.gov"
themesDir               : "./themes"

MetaDataFormat          : "yaml"
DefaultContentLanguage  : "en"
SectionPagesMenu        : "main"
Paginate                : 20
googleAnalytics         : ""
enableRobotsTXT         : true
enableEmoji             : true
enableGitInfo           : true
buildFuture             : true

ignoreFiles:
  - "^_template"
  - "content/_tmp/*"
  - "content/images/*"
  - "content/_archived/*"

sitemap:
  changefreq            : "monthly"
  priority              : 0.5
  filename              : "sitemap.xml"

outputFormats:
  SiteImages:
    mediaType: "application/json"
    baseName: "siteimages"
    isPlainText: true
    notAlternative: true
  RSS:
    mediatype: "application/rss"
  JSON:
    mediatype: "application/json"

outputs:
  home: ["HTML","RSS", "SiteImages", "JSON"]
  section: ["HTML","RSS", "JSON"]
  page: ["HTML","RSS", "JSON"]
  taxonomy: ["HTML","RSS", "JSON"]
  taxonomyTerm: ["HTML","RSS", "JSON"]

blackfriday:
  fractions: false

params:
  description           : "We're making digital in government better, together."
  cdnurl                : "https://s3.amazonaws.com/digitalgov"
  git_org               : "GSA"
  git_repo              : "digitalgov.gov"
  url_shortener_login: jeremyz
  url_shortener_api: d0ac464a2dfad044147e9537fd51503b
  devmode               : false

permalinks:
  posts                 : ":year/:month/:day/:slug/"
  events                : "event/:year/:month/:day/:slug/"

preserveTaxonomyNames   : true
taxonomies:
  tag                   : "tag"
  topic                 : "topics"
  category              : "categories"
  author                : "authors"

## Menu Navigation
menu:
  primary:
    - Name            : "News"
      URL             : "/posts/"
      Weight          : 1
    - Name            : "Events"
      URL             : "/events/"
      Weight          : 2
    - Name            : "Resources"
      URL             : "/resources/"
      Weight          : 3
    - Name            : "Communities"
      URL             : "/communities/"
      Weight          : 4
    - Name            : "People"
      URL             : "/people/"
      Weight          : 4
