title                   : "Digital.gov - Better Digital in Government"
baseURL                 : "/"
languageCode            : "en-us"
theme                   : "digital.gov"
themesDir               : "./themes"

MetaDataFormat          : "yaml"
DefaultContentLanguage  : "en"
SectionPagesMenu        : "main"
Paginate                : 20
googleAnalytics         : ""
enableRobotsTXT         : true
enableEmoji             : true
enableGitInfo           : true
buildFuture             : true

ignoreFiles:
  - "^_template"
  - "content/_tmp/*"
  - "content/images/*"
  - "content/_archived/*"

sitemap:
  changefreq            : "monthly"
  priority              : 0.5
  filename              : "sitemap.xml"

outputFormats:
  SiteImages:
    mediaType: "application/json"
    baseName: "siteimages"
    isPlainText: true
    notAlternative: true
  RSS:
    mediatype: "application/rss"
  JSON:
    mediatype: "application/json"

preserveTaxonomyNames   : true
taxonomies:
  topic                 : "topics"
  author                : "authors"

outputs:
  home: ["HTML","RSS", "SiteImages", "JSON"]
  section: ["HTML","RSS", "JSON"]
  page: ["HTML","RSS", "JSON"]
  taxonomy: ["HTML","RSS", "json"]

blackfriday:
  fractions: false

params:
  description           : "The guides, resources, tools, and services for making digital better in government"
  cdnurl                : "https://s3.amazonaws.com/digitalgov"
  git_org               : "GSA"
  git_repo              : "digitalgov.gov"
  url_shortener_login: jeremyz
  url_shortener_api: d0ac464a2dfad044147e9537fd51503b
  devmode               : false

  # Homepage settings
  dg_tagline: "Build better digital services"

  # number of news items to include on the homepage
  stream_count: 10

  # number of events to include on the homepage
  events_count: 3


relativeURLs: true
refLinksNotFoundURL: https://digital.gov/resources/

permalinks:
  posts                 : ":year/:month/:day/:slug/"
  events                : "event/:year/:month/:day/:slug/"

pluralizelisttitles     : false

menu:
  primary:
    - Name            : "News"
      URL             : "/posts/"
      Weight          : 1
    - Name            : "Events"
      URL             : "/events/"
      Weight          : 2
    - Name            : "Resources"
      URL             : "/resources/"
      Weight          : 3
    - Name            : "Communities"
      URL             : "/communities/"
      Weight          : 4
    - Name            : "Services"
      URL             : "/services/"
      Weight          : 5
