version: 2

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/project
    environment:
      HUGO_BUILD_DIR: ~/project/public

    steps:
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends git
      - checkout
      - run: hugo -v -s ${HUGO_BUILD_DIR}
      - run: ls -all ~/project

      # Run a step to print what branch our code base is on.
      - run:
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}

      # Run a step to print the Authors API path in CircleCi
      - run:
          name: "Authors API path"
          command: echo ${HUGO_BUILD_DIR}/authors/v1/json/

      - run:
          name: Check Authors API $CIRCLE_BRANCH
          command: curl ${HUGO_BUILD_DIR}/authors/v1/json/ | jq
          # command: curl https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/${CIRCLE_BRANCH}/authors/v1/json/ | jq

      # - run:
      #     name: Check Topics API
      #     command: curl https://digital.gov/topics/v1/json/ | jq

      # - restore_cache:
      #     keys:
      #       - dg-cache-v1-{{ .Branch }}-{{ .Revision }}
      #       - dg-cache-v1-{{ .Branch }}
      #       - dg-cache-v1
      #
      # - run:
      #     name: Install NPM Dependencies
      #     command: npm install
      #
      # - run:
      #     name: Install Gulp
      #     command: sudo npm install gulp -g
      #
      # - save_cache:
      #     key: dg-cache-v1-{{ .Branch }}-{{ .Revision }}
      #     paths:
      #       - node_modules
      #
      # - run:
      #     name: NPM Install
      #     command: |
      #       npm install
      #       node -v
      #
      # - run:
      #     name: Image Prep
      #     command: gulp img-prep
      #
      # - run:
      #     name: Image Process
      #     command: gulp img-process
      #
      # - run:
      #     name: Image Upload
      #     command: gulp img-process
      #
      # - run:
      #     name: Image Commit
      #     command: |
      #       git config --global -l
      #       git config --global user.email "jeremy.zilar@gsa.gov"
      #       git config --global user.name "Jeremy Zilar"
      #       gulp img-commit
      #
      # - save_cache:
      #     key: v1-npm-cache-{{ .Branch }}-{{ .Revision }}
      #     paths:
      #       - node_modules
