version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Install Node dependencies
          command: npm install
      - run:
          name: Process images
          command: gulp process-img
