version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-node-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package-lock.json" }}
            - v1-npm-
      - run:
          name: PWD
          command: pwd
      - run:
          name: PWD
          command: ls -all
      - run:
          name: Install Node dependencies
          command: npm install
      - run:
          name: Install Gulp
          command: npm i -g gulp
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Process images
          command: gulp process-img
