version: 2.1

orbs:
  hugo: circleci/hugo@0.5.2

jobs:
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test APIs
          command: |
            cat public/{authors,images,topics}/v1/json/index.html | \
            jq -e . >/dev/null 2>&1

workflows:
  build_and_test:
    jobs:
      - hugo/build:
          html-proofer: false
          version: "0.66.0"
      - test:
          requires:
            - hugo/build
