version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-node-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-cache-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install Node dependencies
          command: npm install --ignore-scripts --verbose
      - save_cache:
          key: v1-npm-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - node_modules
      - run:
          name: install gulp
          command: sudo npm install gulp -g
      - run:
          name: Gulp Version
          command: gulp -v
      - run:
          name: Process images
          command: gulp process-img
